""" 

Revision ID: 054a590783e0
Revises: cc9518ba4cad
Create Date: 2025-02-10 00:15:30.981652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '054a590783e0'
down_revision = 'cc9518ba4cad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device_info', schema=None) as batch_op:
        batch_op.drop_column('version')

    # ### end Alembic commands ###
