""" 

Revision ID: 2fa4f71c4130
Revises: e0e76ec9c0c2
Create Date: 2024-09-06 20:50:24.323895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fa4f71c4130'
down_revision = 'e0e76ec9c0c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('influx_query', schema=None) as batch_op:
        batch_op.add_column(sa.Column('interface_columns', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('influx_query', schema=None) as batch_op:
        batch_op.drop_column('interface_columns')

    # ### end Alembic commands ###
