"""Added reachability_status column to DeviceInfo

Revision ID: 856cf540ed70
Revises: a71a54d5c550
Create Date: 2025-02-23 15:11:07.259686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '856cf540ed70'
down_revision = 'a71a54d5c550'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reachability_status', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device_info', schema=None) as batch_op:
        batch_op.drop_column('reachability_status')

    # ### end Alembic commands ###
