""" 

Revision ID: a71a54d5c550
Revises: 054a590783e0
Create Date: 2025-02-10 19:29:11.192236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a71a54d5c550'
down_revision = '054a590783e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('serial_number', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('model', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('up_time', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('last_reboot_reason', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device_info', schema=None) as batch_op:
        batch_op.drop_column('last_reboot_reason')
        batch_op.drop_column('up_time')
        batch_op.drop_column('model')
        batch_op.drop_column('serial_number')

    # ### end Alembic commands ###
