"""Add unique constraint to user_id and pattern in TrainingData

Revision ID: cc9518ba4cad
Revises: af65ad16c790
Create Date: 2024-11-14 23:50:57.201880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc9518ba4cad'
down_revision = 'af65ad16c790'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_training_data_user_id'), ['user_id'], unique=False)
        batch_op.create_unique_constraint('unique_user_pattern', ['user_id', 'pattern'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_data', schema=None) as batch_op:
        batch_op.drop_constraint('unique_user_pattern', type_='unique')
        batch_op.drop_index(batch_op.f('ix_training_data_user_id'))

    # ### end Alembic commands ###
