outputs:
  default:
    address: http://localhost:8086
    bucket: metrics
    org: juniper
    precision: ns
    token: g84qg1Dz4GxjuAqioniTJsl1K_ln3JVPiU4FshYJ3fUjS5n38cgAMtCcLIBt_TVtmf8IWLfV_wxym-f4v85qjw==
    type: influxdb
subscriptions:
  svla-q5240-06_interfaces_interface_state_counters:
    encoding: proto
    mode: stream
    paths:
    - /interfaces/interface/state/counters
    sample_interval: 10s
  svla-q5240-06_network-instances_network-instance_protocols_protocol_bgp_neighbors_neighbor_state:
    encoding: proto
    mode: stream
    paths:
    - /network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/state
    sample_interval: 10s
  svla-q5240-08_interfaces_interface_state_counters:
    encoding: proto
    mode: stream
    paths:
    - /interfaces/interface/state/counters
    sample_interval: 10s
  svla-q5240-08_network-instances_network-instance_protocols_protocol_bgp_neighbors_neighbor_state:
    encoding: proto
    mode: stream
    paths:
    - /network-instances/network-instance/protocols/protocol/bgp/neighbors/neighbor/state
    sample_interval: 10s
targets:
  svla-q5240-06:
    address: svla-q5240-06:8080
    insecure: true
    password: Embe1mpls
    tls:
      enabled: false
    username: root
  svla-q5240-08:
    address: svla-q5240-08:8080
    insecure: true
    password: Embe1mpls
    tls:
      enabled: false
    username: root
